---
title: "Island Nations Covid Analysis"
author: "Arjun Nanning Ramamurthy"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages, message=FALSE, warning=FALSE}
library(here)
library(tidyverse)
library(lubridate)
```


```{r import-data, echo=FALSE, warning=FALSE, message=FALSE}
island_covid_data <- read_csv(here("data", "island_covid_data.csv"))
```

```{r select-relevant-rows}
rel_data <- island_covid_data %>% 
  filter(population > 1000000) %>% 
  select(location, date, new_cases_per_million, new_cases_smoothed_per_million, new_deaths_per_million, new_deaths_smoothed_per_million)

glimpse(rel_data)
```

```{r new_cases_plot}
rel_data %>% 
  ggplot(aes(x = date, y = new_cases_per_million, colour = location)) + 
  geom_line() +
  labs(
    title = "New Covid cases over time",
    subtitle = "For countries with over 1 million people",
    x = "Date",
    y = "Number of new cases per million"
  ) + 
  theme_minimal()
```

```{r new_cases_smoothed_plot}
rel_data %>% 
  ggplot(aes(x = date, y = new_cases_smoothed_per_million, colour = location)) + 
  geom_line() +
  labs(
    title = "New Covid cases over time",
    subtitle = "For countries with over 1 million people",
    x = "Date",
    y = "Number of new cases per million, 7-day smoothed"
  ) + 
  theme_minimal()
```

```{r max-new-cases}
rel_data %>% 
  arrange(desc(new_cases_per_million))
```

```{r new_deaths_smoothed_plot}
rel_data %>% 
  ggplot(aes(x = date, y = new_deaths_smoothed_per_million, colour = location)) + 
  geom_line() +
  labs(
    title = "New Covid deaths over time",
    subtitle = "For countries with over 1 million people",
    x = "Date",
    y = "Number of new deaths per million, 7-day smoothed"
  ) + 
  theme_minimal()
```

```{r max-new-cases}
rel_data %>% 
  arrange(desc(new_deaths_per_million))
```

```{r weekly-cases, eval=FALSE, include=FALSE}
rel_data %>% 
  mutate()
```


